remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: Louis Hodge
logo: "/images/LH-headshot.jpg"
description: 
  Economist. Education Policy.
  <br>
  Research Leader @ <a href = "https://www.rand.org/about/people/h/hodge_louis.html" rel="noopener noreferrer">RAND Europe</a>.
  <br>
  Formally, <a href = "https://epi.org.uk/author/lhodge/" rel="noopener noreferrer">EPI</a>, <a href = "https://www.gov.uk/government/organisations/department-for-education" rel="noopener noreferrer">DfE</a> and <a href = "https://ifs.org.uk/people/louis-hodge" rel="noopener noreferrer">IFS</a>.
color-scheme: dark

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-sitemap

platforms:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/louis-hodge
  - name: Google Scholar
    icon: <i class="fa-brands fa-google-scholar"></i>
    link: https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=qQuNQ4YAAAAJ
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/l-hodge
  - name: X
    icon: <i class="fa-brands fa-x-twitter"></i>
    link: https://x.com/louis_hodge_

author: Louis Hodge
url: https://l-hodge.github.io/personal-site/
social:
  name: Louis Hodge
  links:
    - https://x.com/louis_hodge_
    - https://github.com/l-hodge
    - https://www.linkedin.com/in/louis-hodge

collections:
  returns-to-education:
    output: true
    permalink: /:collection/:name
  school-system-and-performance:
    output: true
    permalink: /:collection/:name
  other-research:
    output: true
    permalink: /:collection/:name