title: Louis Hodge
logo: "/images/LH-headshot.jpg"
description: >
  <br> <br>
  This is a site about me...
  <br> <br> <br>
  <a href="https://www.linkedin.com/in/louis-hodge/">View My LinkedIn Profile</a> 
  
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
- jekyll-remote-theme
#google_analytics: UA-000000-0
